import streamlit as st
import pandas as pd
import os
from PIL import Image
import joblib
import numpy as np

# Setup page config
st.set_page_config(page_title="Extension Drift Detector", page_icon="🛡️", layout="wide")

# Custom CSS for styling
st.markdown("""
<style>
    .metric-card {
        background-color: #1E1E1E;
        padding: 20px;
        border-radius: 10px;
        color: white;
        text-align: center;
        border: 1px solid #333;
    }
    .suspicious {
        color: #FF4B4B;
        font-weight: bold;
    }
    .normal {
        color: #00CC96;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# Main Title
st.title("🛡️ Browser Extension Anomaly Detector")
st.markdown("Early Detection of Malicious Ownership Transactions in Browser Extensions via Temporal Behavior Drift")

# Load Data
@st.cache_data
def load_data():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(script_dir, "..", "data", "processed", "results_dataset.csv")
    if os.path.exists(data_path):
        return pd.read_csv(data_path)
    return pd.DataFrame()

df = load_data()

if df.empty:
    st.error("No data found! Please make sure you have run the preprocessing and model training scripts.")
else:
    # Sidebar
    st.sidebar.header("Dashboard Controls")
    st.sidebar.markdown("Filter extensions by risk level to analyze behavioral drift.")
    
    # Overview Metrics
    col1, col2, col3 = st.columns(3)
    
    total_extensions = len(df['Extension_ID'].unique())
    suspicious_count = len(df[df['Predicted_Label'] == 1])
    normal_count = total_extensions - suspicious_count
    
    with col1:
        st.markdown(f"<div class='metric-card'><h3>Total Records</h3><h1>{len(df)}</h1></div>", unsafe_allow_html=True)
    with col2:
        st.markdown(f"<div class='metric-card'><h3 class='normal'>Normal Behavior</h3><h1>{normal_count}</h1></div>", unsafe_allow_html=True)
    with col3:
        st.markdown(f"<div class='metric-card'><h3 class='suspicious'>Anomalies Detected</h3><h1>{suspicious_count}</h1></div>", unsafe_allow_html=True)
        
    st.markdown("---")
    
    # Filter Data
    filter_option = st.sidebar.selectbox("Filter Extensions", ["All", "Suspicious Only", "Normal Only"])
    
    if filter_option == "Suspicious Only":
        display_df = df[df['Predicted_Label'] == 1]
    elif filter_option == "Normal Only":
        display_df = df[df['Predicted_Label'] == 0]
    else:
        display_df = df
        
    # Tab layout
    tab1, tab2, tab3 = st.tabs(["📊 Data Table & Risk Scores", "📉 Anomaly Analysis Charts", "🧪 Test Live Extension"])
    
    with tab1:
        st.subheader("Extension Behavior Logs")
        
        # Displaying a formatted dataframe
        show_df = display_df[['Extension_ID', 'Week', 'Permissions_Count', 'Network_Requests', 'Cookie_Access', 'API_Calls', 'Predicted_Label', 'Anomaly_Score']].copy()
        
        # Format columns for better readability
        show_df['Status'] = show_df['Predicted_Label'].apply(lambda x: "🚨 Suspicious" if x == 1 else "✅ Normal")
        show_df = show_df.drop(columns=['Predicted_Label'])
        
        # Sort by Anomaly Score (lowest first = most anomalous)
        show_df = show_df.sort_values(by='Anomaly_Score', ascending=True)
        
        st.dataframe(show_df, use_container_width=True, height=400)
        
    with tab2:
        st.subheader("Visual Analysis of Behavioral Drift")
        st.markdown("These charts are generated by our Isolation Forest Machine Learning model.")
        
        col_img1, col_img2 = st.columns(2)
        
        with col_img1:
            script_dir = os.path.dirname(os.path.abspath(__file__))
            dist_path = os.path.join(script_dir, "..", "reports", "anomaly_scores_dist.png")
            if os.path.exists(dist_path):
                img = Image.open(dist_path)
                st.image(img, caption="Distribution of Anomaly Scores", use_container_width=True)
            else:
                st.warning("Score distribution plot not found.")
                
        with col_img2:
            script_dir = os.path.dirname(os.path.abspath(__file__))
            scatter_path = os.path.join(script_dir, "..", "reports", "anomaly_scatter.png")
            if os.path.exists(scatter_path):
                img = Image.open(scatter_path)
                st.image(img, caption="Isolation Forest Detection: Permissions vs Network Requests", use_container_width=True)
            else:
                st.warning("Scatter plot not found.")
                
    with tab3:
        st.subheader("Test an Extension Live")
        st.markdown("Enter the name and behavioral statistics of an extension to see if the AI flags it as suspicious.")
        
        extension_name = st.text_input("Extension Name (e.g., AdBlocker, Gramarly)", value="My Extension")
        
        test_col1, test_col2 = st.columns(2)
        
        with test_col1:
            perm_count = st.number_input("Permissions Count", min_value=0, max_value=50, value=2)
            net_reqs = st.number_input("Network Requests (per week)", min_value=0, max_value=5000, value=10)
            
        with test_col2:
            api_calls = st.number_input("API Calls", min_value=0, max_value=2000, value=15)
            cookie_access = st.selectbox("Accesses Cookies?", ["No", "Yes"])
            cookie_val = 1 if cookie_access == "Yes" else 0
            
        if st.button("Analyze Extension", type="primary"):
            st.info("Analyzing your extension...")
            try:
                # Load models
                script_dir = os.path.dirname(os.path.abspath(__file__))
                scaler_path = os.path.join(script_dir, "..", "models", "scaler.pkl")
                model_path = os.path.join(script_dir, "..", "models", "isolation_forest.pkl")
                
                if os.path.exists(scaler_path) and os.path.exists(model_path):
                    scaler = joblib.load(scaler_path)
                    model = joblib.load(model_path)
                    
                    # Prepare input
                    input_data = pd.DataFrame([[perm_count, net_reqs, cookie_val, api_calls]], 
                                             columns=['Permissions_Count', 'Network_Requests', 'Cookie_Access', 'API_Calls'])
                    
                    # Scale input
                    input_scaled = scaler.transform(input_data)
                    
                    # Predict
                    prediction = model.predict(input_scaled)
                    score = model.decision_function(input_scaled)[0]
                    
                    # 1 is normal, -1 is anomaly in Isolation Forest
                    if prediction[0] == 1:
                        st.success(f"✅ **NORMAL** - **{extension_name}** appears safe. (Anomaly Score: {score:.3f})")
                    else:
                        st.error(f"🚨 **SUSPICIOUS** - **{extension_name}** is exhibiting behavioral drift! (Anomaly Score: {score:.3f})")
                    
                    st.write(f"**Debug Info:** Raw Prediction = {prediction[0]}, Raw Score = {score:.4f}")
                else:
                    st.error("Error: Could not find the trained model or scaler. Please run preprocessing and training scripts.")
            except Exception as e:
                st.error(f"An error occurred during prediction: {e}")
